### ISSUE TITLE
What is this about? 

### ISSUE THREAD

**Issue by ashleyasmus** [RSGInc/travelSurveyTools#157]
Why is there a dangling hts_data here? What is it doing?
https://github.com/RSGInc/travelSurveyTools/blob/1f3ff6bb334987dd01b96271f88ad10c45cfb787/R/hts_prep_triprate.R#L61

**Comment by erika-redding** [comment]
I think we should update this argument to the proper format, similar to the example code or as it appear in this function here: https://github.com/RSGInc/travelSurveyTools/blob/1f3ff6bb334987dd01b96271f88ad10c45cfb787/R/hts_prep_variable.R#L73

Do you agree @ashleyasmus?

**Comment by ashleyasmus** [comment]
I agree
