### ISSUE TITLE
Print warning message anytime outliers are removed!

### ISSUE THREAD

**Issue by ashleyasmus** [RSGInc/travelSurveyTools#159]
https://github.com/RSGInc/travelSurveyTools/blob/1f3ff6bb334987dd01b96271f88ad10c45cfb787/R/hts_remove_outliers.R#L16

**Comment by joe-chestnut** [comment]
I'd add to this that we should not have outliers removed as the default. https://github.com/RSGInc/travelSurveyTools/blob/1f3ff6bb334987dd01b96271f88ad10c45cfb787/R/hts_prep_triprate.R#L58C30-L58C46 

It seems to me that if we want to remove data we should make sure the person doing it has to take steps to do so.
